travelmanagementsystem-portal/src/main/java/com/truemega/beans/administration/AirLineListBean.java
package com.truemega.beans.administration;

import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.event.AjaxBehaviorEvent;

import com.truemega.beans.TravelListBean;
import com.truemega.dto.AirlineDTO;
import com.truemega.interfaces.administration.AirLineService;

@ManagedBean(name = "airlinelist")
@ViewScoped
public class AirLineListBean extends TravelListBean {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@EJB
	private AirLineService airLineService;
	private List<AirlineDTO> airlineDTOs;

	@Override
	public String getScreenName() {
		// TODO Auto-generated method stub
		return "administration/airlinelist.xhtml";
	}

	@Override
	public void search() {
		// TODO Auto-generated method stub

	}

	@Override
	public void reset() {
		// TODO Auto-generated method stub

	}

	@Override
	public void delete() {
		// TODO Auto-generated method stub

	}

	@PostConstruct
	@Override
	public void load() {
		// TODO Auto-generated method stub

		try {
			airlineDTOs = airLineService.getAllAirLines(getUserName());

		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
	}

	public void changeStatus(AjaxBehaviorEvent event) {

		try {
			AirlineDTO airlineDTO = (AirlineDTO) event.getComponent()
					.getAttributes().get("airlinemodel");

			airLineService.changeStatus(airlineDTO.getStatus(),
					airlineDTO.getId(), getUserName());

			load();
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}

	}

	@Override
	public boolean validate() {
		// TODO Auto-generated method stub
		return false;
	}

	public List<AirlineDTO> getAirlineDTOs() {
		return airlineDTOs;
	}

	public void setAirlineDTOs(List<AirlineDTO> airlineDTOs) {
		this.airlineDTOs = airlineDTOs;
	}

}

travelmanagementsystem-portal/src/main/java/com/truemega/beans/administration/AirLineSingleBean.java
package com.truemega.beans.administration;

import java.util.Date;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import com.truemega.beans.TravelSingleBean;
import com.truemega.dto.AirlineDTO;
import com.truemega.enums.Status;
import com.truemega.enums.UIOperation;
import com.truemega.interfaces.administration.AirLineService;
import com.truemega.logger.LoggerService;
import com.truemega.sessionbeans.Entity;
import com.truemega.sessionbeans.Screen;
import com.truemega.utils.HttpJSFUtils;


@ManagedBean(name = "airlinesingle")
@ViewScoped
public class AirLineSingleBean  extends TravelSingleBean {

	
	private static final long serialVersionUID = 1L;
	

    
	private LoggerService loggerService = new LoggerService();
	
	@EJB
	private AirLineService  airLineService ;
	
	private AirlineDTO airlineDTO  = new AirlineDTO() ;
	private AirlineDTO oldAirlineDTO  = new AirlineDTO() ;
	private Integer airLineId;
	
	
	@PostConstruct
	public void init() {

		Screen screen = (Screen) HttpJSFUtils.getSession().getAttribute(
				"screen");
		switch (screen.getScreenMode()) {
		case 0:
			screenMode = UIOperation.ADD;
			break;
		case 1:
			screenMode = UIOperation.UPDATE;
			load();
			break;
		case 2:
			screenMode = UIOperation.VIEW;
			load();
			break;
		}


	}
	
	@Override
	public void save() {
		// TODO Auto-generated method stub
		
		loggerService.logPortalInfo(" start save method of AirLineSingleBean ");
		boolean isValid = validate();
		if (isValid) {

			try {

				airlineDTO.setSystemUser(getUserName());
				airlineDTO.setModificationDate(new Date());

				airlineDTO = airLineService.saveAirLine(airlineDTO,
						getUserName());

				screenMode = UIOperation.VIEW;
				operationStatus = Status.SUCCESS;
			} catch (Exception e) {
				// TODO: handle exception
				e.printStackTrace();
				operationStatus = Status.FAIL;
				operationMessage = "Invalid Data";
				loggerService.logPortalError("can't save airlineDTO ", e);
			}
			
		}else {
			// Error Message
			screenMode = UIOperation.ADD;
			operationStatus = Status.FAIL;
			operationMessage = "This AirLine already exist. ";
		}
		
		loggerService.logPortalInfo(" end save method of AirLineSingleBean ");
		
	
		
	}
	@Override
	public void update() {
		// TODO Auto-generated method stub

		loggerService.logPortalInfo(" start update method of AirLineSingleBean ");
		boolean isValid = validate();
		if (isValid) {

			try {

				airlineDTO.setSystemUser(getUserName());
				airlineDTO.setModificationDate(new Date());

				airlineDTO = airLineService.updateAirLine(airlineDTO,
						getUserName());

				screenMode = UIOperation.VIEW;
				operationStatus = Status.SUCCESS;
			} catch (Exception e) {
				// TODO: handle exception
				e.printStackTrace();
				operationStatus = Status.FAIL;
				operationMessage = "Invalid Data";
				loggerService.logPortalError("can't update airlineDTO ", e);
			}
			
		}else {
			// Error Message
			screenMode = UIOperation.UPDATE;
			operationStatus = Status.FAIL;
			operationMessage = "This AirLine already exist. ";
		}
		
		loggerService.logPortalInfo(" end update method of AirLineSingleBean ");
		
	
		
	
	}
	@Override
	public void load() {

		loggerService
				.logPortalInfo(" start load method of AirLineSingleBean ");
		try {
			Entity entity = (Entity) HttpJSFUtils.getSession().getAttribute(
					"entity");
			if (entity != null)
				airLineId = entity.getEntityId();

			airlineDTO = airLineService.findAirLineById(airLineId,
					getUserName());

			
			oldAirlineDTO = airlineDTO ;
			
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
			loggerService.logPortalError("can't load  ", e);
		}
		loggerService.logPortalInfo(" end load method of AirLineSingleBean ");
	
	
	}
	@Override
	public boolean validate() {
		// TODO Auto-generated method stub


		if (screenMode.equals(UIOperation.ADD)) {
			return airLineService.checkUniqueAirLineName(airlineDTO.getName());
		} else {
		
		 AirlineDTO  tempAirLineDTO =  airLineService.findAirLineByName(airlineDTO.getName(), getUserName());
		 if(tempAirLineDTO == null)
			 return true  ;
			 else
			 {
				 if(tempAirLineDTO.getId() == airlineDTO.getId() )
					 return true ;
				 else
				 {
					 operationMessage = "This AirLine already exist. ";
					 return false ;
					 
				 }
				 
			 }
		}
	
	
	}
	public AirlineDTO getAirlineDTO() {
		return airlineDTO;
	}
	public void setAirlineDTO(AirlineDTO airlineDTO) {
		this.airlineDTO = airlineDTO;
	}
	public AirlineDTO getOldAirlineDTO() {
		return oldAirlineDTO;
	}
	public void setOldAirlineDTO(AirlineDTO oldAirlineDTO) {
		this.oldAirlineDTO = oldAirlineDTO;
	}
	public Integer getAirLineId() {
		return airLineId;
	}
	public void setAirLineId(Integer airLineId) {
		this.airLineId = airLineId;
	}
	
}

travelmanagementsystem-portal/src/main/java/com/truemega/beans/administration/InvoiceTemplateDownloaderBean.java
package com.truemega.beans.administration;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

import com.truemega.logger.LoggerService;

@ManagedBean(name = "invoiceTemplate")
@ViewScoped
public class InvoiceTemplateDownloaderBean {

	private static final long serialVersionUID = 1L;

	private LoggerService loggerService = new LoggerService();

	private StreamedContent reportFile;

	@PostConstruct
	public void init() {
	}

	public StreamedContent getReportFile() {
		String outputFilePath = "." + File.separator + "TravelManagement"
				+ File.separator + "InvoiceTemplate" + File.separator
				+ "Travel_Template.xlsx";

		try {
			File reportingFile = new File(outputFilePath);
			InputStream stream = null;
			stream = new FileInputStream(reportingFile);
			reportFile = new DefaultStreamedContent(stream,
					"application/vnd.ms-outlook", reportingFile.getName());
			return reportFile;
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			loggerService.logPortalError("Error reading template", e);
			e.printStackTrace();
			return null;
		} catch (Exception e) {
			// TODO Auto-generated catch block
			loggerService.logPortalError("Error reading template", e);
			e.printStackTrace();
			return null;
		}

	}

	public void setReportFile(StreamedContent reportFile) {
		this.reportFile = reportFile;
	}
}

travelmanagementsystem-portal/src/main/java/com/truemega/beans/administration/MaxMinSingleBean.java
package com.truemega.beans.administration;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import com.truemega.beans.TravelSingleBean;
import com.truemega.dto.MaxMinValuesDTO;
import com.truemega.enums.Status;
import com.truemega.enums.UIOperation;
import com.truemega.interfaces.administration.MaxMinService;
import com.truemega.interfaces.notification.UploadNotificationSender;
import com.truemega.logger.LoggerService;
import com.truemega.sessionbeans.Screen;
import com.truemega.utils.HttpJSFUtils;

@ManagedBean(name = "maxminsingle")
@ViewScoped
public class MaxMinSingleBean extends TravelSingleBean {

	private static final long serialVersionUID = 1L;

	private LoggerService loggerService = new LoggerService();

	@EJB
	private MaxMinService maxMinService;
	@EJB
	private UploadNotificationSender notification;

	private MaxMinValuesDTO visa = null;
	private MaxMinValuesDTO medicalInsurance = null;
	private MaxMinValuesDTO airplaneMax = null;
	private MaxMinValuesDTO airplanemin = null;

	private List<MaxMinValuesDTO> maxMinValuesDTOs = new ArrayList<MaxMinValuesDTO>();

	private Integer maxminId;

	@PostConstruct
	public void init() {

		Screen screen = (Screen) HttpJSFUtils.getSession().getAttribute(
				"screen");
		switch (screen.getScreenMode()) {
		case 0:
			screenMode = UIOperation.ADD;
			load();
			break;
		case 1:
			screenMode = UIOperation.UPDATE;
			load();
			break;
		case 2:
			screenMode = UIOperation.VIEW;
			load();
			break;
		}

	}

	@Override
	public void save() {

		// TODO Auto-generated method stub

		loggerService
				.logPortalInfo(" start update method of MaxMinSingleBean ");
		boolean isValid = validate();
		if (isValid) {

			try {

				maxMinService.updateMaxsMinsValues(maxMinValuesDTOs,
						getUserName());
				screenMode = UIOperation.VIEW;
				operationStatus = Status.SUCCESS;
			} catch (Exception e) {
				// TODO: handle exception
				e.printStackTrace();
				operationStatus = Status.FAIL;
				operationMessage = "Invalid Data";
				loggerService.logPortalError("can't update airlineDTO ", e);
			}

		} else {
			// Error Message
			screenMode = UIOperation.UPDATE;
			operationStatus = Status.FAIL;
			operationMessage = "This AirLine already exist. ";
		}

		loggerService.logPortalInfo(" end update method of MaxMinSingleBean ");

	}

	@Override
	public void update() {
	}

	public void uploadNotification() {

		// notification.sendNotificationInvoiceUploaded();

	}

	public void maxinsurancePeriod() {
		// notification.sendNotificationMaxInsurancePeriod();
	}

	public void unknownHotls() {

		// notification.sendNotificationNotificationReservationUnknownHotel();

	}

	public void maxVisaPeriod() {

		// notification.sendNotificationMaxVisaPeriod();

	}

	public void maxAirLineTicket() {

		// notification.sendNotificationMaxAirLineTicket();

	}

	public void minAirLineTicket() {

		// notification.sendNotificationMinAirLineTicket();

	}

	public void hotelRateAbovePreNegotiatedRates() {

		// notification.sendNotificationHotelRateAbovePreNegotiatedRates();

	}

	public void hotelRateBelowPreNegotiatedRates() {

		// notification.sendNotificationHotelRateBelowPreNegotiatedRates();

	}

	@Override
	public void load() {

		loggerService.logPortalInfo(" start load method of MaxMinSingleBean ");
		maxMinValuesDTOs = maxMinService.getAllMaxMinValuess(getUserName());

		try {

			visa = maxMinValuesDTOs.get(0);
			medicalInsurance = maxMinValuesDTOs.get(1);
			airplaneMax = maxMinValuesDTOs.get(2);
			airplanemin = maxMinValuesDTOs.get(3);

		} catch (Exception e) {
			// TODO: handle exception

			loggerService.logPortalError("can't load  ", e);
		}
		loggerService.logPortalInfo(" end load method of MaxMinSingleBean ");

	}

	@Override
	public boolean validate() {

		return true;
	}

	public MaxMinValuesDTO getVisa() {
		return visa;
	}

	public void setVisa(MaxMinValuesDTO visa) {
		this.visa = visa;
	}

	public MaxMinValuesDTO getMedicalInsurance() {
		return medicalInsurance;
	}

	public void setMedicalInsurance(MaxMinValuesDTO medicalInsurance) {
		this.medicalInsurance = medicalInsurance;
	}

	public MaxMinValuesDTO getAirplaneMax() {
		return airplaneMax;
	}

	public void setAirplaneMax(MaxMinValuesDTO airplaneMax) {
		this.airplaneMax = airplaneMax;
	}

	public MaxMinValuesDTO getAirplanemin() {
		return airplanemin;
	}

	public void setAirplanemin(MaxMinValuesDTO airplanemin) {
		this.airplanemin = airplanemin;
	}

	public Integer getMaxminId() {
		return maxminId;
	}

	public void setMaxminId(Integer maxminId) {
		this.maxminId = maxminId;
	}

}

travelmanagementsystem-portal/src/main/java/com/truemega/beans/administration/ProductListBean.java
package com.truemega.beans.administration;

import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.event.AjaxBehaviorEvent;

import com.truemega.beans.TravelListBean;
import com.truemega.dto.ProductTypeDTO;
import com.truemega.dto.ServiceTypeDTO;
import com.truemega.interfaces.administration.ProductService;
import com.truemega.interfaces.administration.ServiceService;

@ManagedBean(name = "productlist")
@ViewScoped
public class ProductListBean extends TravelListBean {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@EJB
	ServiceService serviceService;
	@EJB
	ProductService productService;

	List<ServiceTypeDTO> serviceTypeDTOs;
	List<ProductTypeDTO> productTypeDTOs;

	@Override
	public String getScreenName() {
		// TODO Auto-generated method stub
		return "administration/productlist.xhtml";
	}

	@Override
	public void search() {
		// TODO Auto-generated method stub

	}

	@Override
	public void reset() {
		// TODO Auto-generated method stub

	}

	@Override
	public void delete() {
		// TODO Auto-generated method stub

	}

	@PostConstruct
	@Override
	public void load() {
		// TODO Auto-generated method stub
		try {
			serviceTypeDTOs = serviceService.getAllServices(getUserName());

			productTypeDTOs = productService.getAllProduct(getUserName());

		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}

	}

	public void changeStatus(AjaxBehaviorEvent event) {

		try {
			ProductTypeDTO product = (ProductTypeDTO) event.getComponent()
					.getAttributes().get("productmodel");

			productService.changeStatus(product.getStatus(), product.getId(),
					getUserName());

			load();
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}

	}

	@Override
	public boolean validate() {
		// TODO Auto-generated method stub
		return true;
	}

	public List<ServiceTypeDTO> getServiceTypeDTOs() {
		return serviceTypeDTOs;
	}

	public void setServiceTypeDTOs(List<ServiceTypeDTO> serviceTypeDTOs) {
		this.serviceTypeDTOs = serviceTypeDTOs;
	}

	public List<ProductTypeDTO> getProductTypeDTOs() {
		return productTypeDTOs;
	}

	public void setProductTypeDTOs(List<ProductTypeDTO> productTypeDTOs) {
		this.productTypeDTOs = productTypeDTOs;
	}

}

travelmanagementsystem-portal/src/main/webapp/administration/airlinesingle.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:composites="http://java.sun.com/jsf/composite/composites">
	
	
<h:head>
	<script type="text/javascript">
		
	</script>
</h:head>

<h:body>
	<ui:composition template="/layout/master-page.xhtml">
		<ui:define name="content">
			<div class="container-fluid left-border">
				<div class="row">
					<div class="col-md-12 col-lg-12 page-header">
						<h1>Add an Airline  </h1>
					</div>
					<div class="col-md-10">
					<p:ajaxStatus onstart="PF('statusDialog').show()"
							onsuccess="PF('statusDialog').hide()" />

						<p:dialog widgetVar="statusDialog" modal="true" draggable="false"
							closable="false" resizable="false" showHeader="false">
							<p:graphicImage value="../images/ajaxloadingbar.gif" />
						</p:dialog>
						<h:form styleClass="form-horizontal" id="formID">
						
							<c:if
								test="#{airlinesingle.screenMode == 'VIEW' and airlinesingle.operationStatus == 'SUCCESS'}">
								<div class="alert alert-success">
									<strong><h:outputText
											value="#{sessionScope.screen.screenName}" /> is added
										successfully ! </strong>
								</div>
							</c:if>
							<c:if
								test="#{airlinesingle.screenMode == 'UPDATE' and airlinesingle.operationStatus == 'SUCCESS'}">

								<div class="alert alert-success">
									<strong><h:outputText
											value="#{sessionScope.screen.screenName}" /> is updated
										successfully ! </strong>
								</div>
							</c:if>
							<c:if test="#{airlinesingle.operationStatus == 'FAIL'}">
								<div class="alert alert-danger">
									<strong>#{airlinesingle.operationMessage}</strong>
								</div>
							</c:if>
							
				
							
				
							<div class="form-group">
								<h:outputLabel value="Airline  Name "
									styleClass="control-label col-xs-3" />
								<div class="col-xs-4">
									<h:inputText value="#{airlinesingle.airlineDTO.name}"
										id="dtName" styleClass="form-control" required="true"
										requiredMessage="Airline Name is required"
										disabled="#{airlinesingle.screenMode == 'VIEW'}">
										</h:inputText>
									<h:message for="dtName" style="color:red" />
								</div>
							</div>
					






							<div class="form-group">
								<div class="col-xs-offset-6 col-xs-6">
									<c:if test="#{airlinesingle.screenMode == 'ADD'}">
										<h:commandButton id="submitButton" value="Save"
											actionListener="#{airlinesingle.save}" styleClass="btn btn-default">
											<f:ajax execute="@form" render="@form" />
										</h:commandButton>
									</c:if>
									<c:if test="#{airlinesingle.screenMode == 'UPDATE'}">
										<h:commandButton id="submitButton" value="Update"
											actionListener="#{airlinesingle.update}"
											styleClass="btn btn-default">
											<f:ajax execute="@form" render="@form" />
										</h:commandButton>
									</c:if>
									<c:if test="#{airlinesingle.screenMode == 'VIEW'}">
										<h:commandButton id="submitButton" value="Back"
											action="#{controller.showPage}" styleClass="btn btn-default">
											<f:setPropertyActionListener target="#{controller.screenURL}"
												value="administration/airlinelist.xhtml" />
											<f:setPropertyActionListener target="#{controller.screeName}"
												value="Airlines Management" />
										</h:commandButton>
									</c:if>
									<c:if
										test="#{airlinesingle.screenMode == 'UPDATE' || airlinesingle.screenMode == 'ADD'}">
										<h:commandButton id="cancelButton" value="Cancel"
											immediate="true" action="#{controller.showPage}"
											styleClass="btn btn-default cancel-margin">
											<f:setPropertyActionListener target="#{controller.screenURL}"
												value="administration/airlinelist.xhtml" />
											<f:setPropertyActionListener target="#{controller.screeName}"
												value="Airlines Management" />
										</h:commandButton>
									</c:if>
								</div>
							</div>
						</h:form>
					</div>

				</div>

			</div>
		</ui:define>
	</ui:composition>
</h:body>
</html>

travelmanagementsystem-portal/src/main/webapp/administration/maxminvalues.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:composites="http://java.sun.com/jsf/composite/composites">


<h:head>
	<script type="text/javascript">
		
	</script>
</h:head>

<h:body>
	<ui:composition template="/layout/master-page.xhtml">
		<ui:define name="content">
			<div class="container-fluid left-border">
				<div class="row">
					<div class="col-md-12 col-lg-12 page-header">
						<h1>Maximum And  Minimum Values</h1>
					</div>
					<div class="col-md-10">
						<p:ajaxStatus onstart="PF('statusDialog').show()"
							onsuccess="PF('statusDialog').hide()" />

						<p:dialog widgetVar="statusDialog" modal="true" draggable="false"
							closable="false" resizable="false" showHeader="false">
							<p:graphicImage value="../images/ajaxloadingbar.gif" />
						</p:dialog>
						<h:form styleClass="form-horizontal" id="formID">

							<c:if
								test="#{maxminsingle.screenMode == 'VIEW' and maxminsingle.operationStatus == 'SUCCESS'}">
								<div class="alert alert-success">
									<strong><h:outputText
											value="#{sessionScope.screen.screenName}" /> is added
										successfully ! </strong>
								</div>
							</c:if>
							<c:if
								test="#{maxminsingle.screenMode == 'UPDATE' and maxminsingle.operationStatus == 'SUCCESS'}">

								<div class="alert alert-success">
									<strong><h:outputText
											value="#{sessionScope.screen.screenName}" /> is updated
										successfully ! </strong>
								</div>
							</c:if>
							<c:if test="#{maxminsingle.operationStatus == 'FAIL'}">
								<div class="alert alert-danger">
									<strong>#{maxminsingle.operationMessage}</strong>
								</div>
							</c:if>




							<div class="form-group">
								<h:outputLabel value="Visa Maximum Period (Days)"
									styleClass="control-label col-xs-3" />
								<div class="col-xs-4">
									<h:inputText value="#{maxminsingle.visa.maxMinValue}" id="visa"
										styleClass="form-control" label="Visa"
										converterMessage="Please enter digits only."
										disabled="#{maxminsingle.screenMode == 'VIEW'}">
									</h:inputText>
									<h:message for="visa" style="color:red" />
								</div>
							</div>

							<div class="form-group">
								<h:outputLabel value=" Medical Insurance Maximum Period (Days) "
									styleClass="control-label col-xs-3" />
								<div class="col-xs-4">
									<h:inputText
										value="#{maxminsingle.medicalInsurance.maxMinValue}"
										id="medical" styleClass="form-control"
										converterMessage="Please enter digits only."
										disabled="#{maxminsingle.screenMode == 'VIEW'}">
									</h:inputText>
									<h:message for="medical" style="color:red" />
								</div>
							</div>
							<div class="form-group">
								<h:outputLabel value="Airplane Max Price  "
									styleClass="control-label col-xs-3" />
								<div class="col-xs-4">
									<h:inputText value="#{maxminsingle.airplaneMax.maxMinValue}"
										id="airplanemax" styleClass="form-control"
										converterMessage="Please enter digits only."
										disabled="#{maxminsingle.screenMode == 'VIEW'}">
									</h:inputText>
									<h:message for="airplanemax" style="color:red" />
								</div>
							</div>
							<div class="form-group">
								<h:outputLabel value="Airplane Min Price "
									styleClass="control-label col-xs-3" />
								<div class="col-xs-4">
									<h:inputText value="#{maxminsingle.airplanemin.maxMinValue}"
										id="airplanemin" styleClass="form-control"
										converterMessage="Please enter digits only."
										disabled="#{maxminsingle.screenMode == 'VIEW'}">
									</h:inputText>
									<h:message for="airplanemin" style="color:red" />
								</div>
							</div>


							<div class="form-group">
								<div class="col-xs-offset-6 col-xs-6">
									<c:if test="#{maxminsingle.screenMode == 'ADD'}">
										<h:commandButton id="submitButton" value="Save"
											actionListener="#{maxminsingle.save}"
											styleClass="btn btn-default">
											<f:ajax execute="@form" render="@form" />
										</h:commandButton>
									</c:if>
									<c:if test="#{maxminsingle.screenMode == 'UPDATE'}">
										<h:commandButton id="submitButton" value="Update"
											actionListener="#{maxminsingle.update}"
											styleClass="btn btn-default">
											<f:ajax execute="@form" render="@form" />
										</h:commandButton>
									</c:if>

									
									<c:if
										test="#{maxminsingle.screenMode == 'UPDATE' || maxminsingle.screenMode == 'ADD'}">
										<h:commandButton id="cancelButton" value="Back"
											immediate="true" action="#{controller.showPage}"
											styleClass="btn btn-default cancel-margin">
											<f:setPropertyActionListener target="#{controller.screenURL}"
												value="index.xhtml" />
											<f:setPropertyActionListener target="#{controller.screeName}"
												value="Max Name " />
										</h:commandButton>
									</c:if>

									<c:if test="#{maxminsingle.screenMode == 'VIEW'}">
										<h:commandButton id="submitButton" value="Back"
											action="#{controller.showPage}" styleClass="btn btn-default">
											<f:setPropertyActionListener target="#{controller.screenURL}"
												value="index.xhtml" />
											<f:setPropertyActionListener target="#{controller.screeName}"
												value="Max Name " />
										</h:commandButton>
									</c:if>
								</div>
							</div>
						</h:form>
					</div>

				</div>

			</div>
		</ui:define>
	</ui:composition>
</h:body>
</html>